import AuthSessionProvider from "@/components/providers/AuthSessionProvider";
import { authOptions } from "@/helpers/nextAuthHandler";
import { cn } from "@/lib/utils";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WeChat by Siam",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={cn(GeistSans.className)}>
        <AuthSessionProvider session={session!}>{children}</AuthSessionProvider>
      </body>
    </html>
  );
}
